version: '3.1'

services:

  postgres_financial_management:
    image: postgres
    environment:
      POSTGRES_DB: financial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/financial-management-database:/var/lib/postgresql/data
